### ISSUE TITLE
NVDA resource monitor and a request.

### ISSUE THREAD

**Issue by ghost** [josephsl/resourceMonitor#1]
Hello.

I Think it would be a nice feature if you could select a drive, For example my d: drive and have it so that when you press NVDA shift three, it would say how much space has been used up and how much space is availible. So instead of hearing c: and d: I would like to only hear the drive I have selected.

Thank you for reading,
Brad.

**Comment by josephsl** [comment]
Hi, this can be done by opening File Explorer (Windows Explorer in earlier versions), select the drive, open its properties and use screen review to review this information. Note that Resource Monitor is not meant to replace tools such as Task Manager, Resource Monitor, Disk Management and others (there is a wonderful utility out there called Speccy that’ll let you see information provided by this add-on as well). Thanks.

**Comment by audiogamer22** [comment]
Hi. Thanks.

Sent from my iPhone

On 26 Nov 2016, at 17:00, Joseph Lee <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, this can be done by opening File Explorer (Windows Explorer in earlier versions), select the drive, open its properties and use screen review to review this information. Note that Resource Monitor is not meant to replace tools such as Task Manager, Resource Monitor, Disk Management and others (there is a wonderful utility out there called Speccy that’ll let you see information provided by this add-on as well). Thanks.
