### ISSUE TITLE
Reported total virtual memory (swap) is not relevant

### ISSUE THREAD

**Issue by CyrilleB79** [josephsl/resourceMonitor#10]
Hi

### Context:
I am monitoring memory on my computer due to an unknown excessive memory usage (audio driver issue? other memory leak?).

### Issue description:
When reporting memory info (NVDA+shift+2), the total virtual memory (swap) that is reported is not the maximum memory that Windows may allocate. It seems that Windows is allocating dynamically swap until a certain amount of memory.

### Step by step issue description:
* Press NVDA+shift+2
  For virtual memory (swap), 5GB/16GB is reported.
* Perform a high memory consuming activity and ask memory information again:
  For virtual memory (swap), 9GB/16GB is reported.
* Perform some more high memory consuming activity and ask memory information again:
  For virtual memory (swap), 13GB/32GB is reported.
* Perform some more high memory consuming activity and ask memory information again:
  For virtual memory (swap), 47GB/48GB is reported.
* Perform some more high memory consuming activity and ask memory information again:
  The computer runs out of memory and applications or Windows itself crashes.

### Actual result:
Resource monitor reports initially 16GB of virtual memory but we can see that Windows may allocate until 48GB of virtual memory at the end.
Also the reported percent do not make sense.

### Expected result:
Report the max amount of memory that Windows may allocate in NVDA+shift+2 command.

### System info:
* Resource monitor 20.01
* NVDA 2020.4beta4
* Windows 10 1809 (64-bit) build 17763.1697

But this issue seems to be present also on other Win 10 systems.

Thanks.

**Comment by josephsl** [comment]
Hi, this is more towards Psutil issue, as NVDA reports what Psutil says. I advise filing an issue against Psuilt for this one (closing as needsexternalfix). Thanks.

**Comment by CyrilleB79** [comment]
Hi Joseph
Sorry for my late answer in this issue.
For you or whoever maintain this add-on.
Even if the issue is coming from the external Psutil subcomponent, I would prefer not to close the current issue.
As the add-on author/maintainer, you have various options:
1. Report the issue to Psutil, put the current issue as blocked / need external fix, and close it when you integrate an updated version of Psutil fixing the issue.
2. Find another solution that do not rely on Psutil, e.g. directly call some Windows API or look for another Python library that would do this job.
Note: Positionning myself as a simple user of this add-on (not author/maintainer, nor potential contributor), I do not intend to open and follow an issue with Psutil, unless I am the only one to experiment the issue described in the current ticket.

**Comment by josephsl** [comment]
Hi, at this time, I may not be able to resolve this with psutil developers in time for end of add-on maintenance from me (this fall). Sorry. Thanks.
