### ISSUE TITLE
[feature request] Settings for verbosity of messages

### ISSUE THREAD

**Issue by falisca** [josephsl/resourceMonitor#11]
For Some languages at the time the messages are long and verbose, maybe a flag in the settings to control verbosity could be interesting.
For Example: "Average CPU load 1.2%, Core 1: 0%, Core 2: 0%, Core 3: ..."
Could be "CPU 1.2%, Core 1: 0%, Core 2: 0%,..." and the same for the command for all statistics: ("60% RAM used, CPU at 9%..." becomes "60% RAM, 12% CPU...")
It could help advanced users to save time :)

**Comment by josephsl** [comment]
Hi, I see. I’ll think about this.

**Comment by josephsl** [comment]
Hi,

As much as I wished to look into this feature, it appears I may need to shelve this for now (closing for now, sorry).

Thanks.
