### ISSUE TITLE
duplicate command for one ressource reporting

### ISSUE THREAD

**Issue by clementb49** [josephsl/resourceMonitor#4]
Hello,
nvda + shift + 5 and nvda + shift + 2 report the same information. Is it normal?

**Comment by josephsl** [comment]
Hi, yes because some keyboards do not work well with Caps lock+Shift+2. Thanks.

**Comment by cartertemm** [comment]
Out of curiosity, by saying it doesn't work well what exactly do you mean? Conflict of some sort?

**Comment by josephsl** [comment]
Hi, no, on some keyboards, NVDA+Shift+2 isn’t registered all the way (the most common combination I’ve seen personally was NVDA+Shift when I did press NVDA+Shift+2). Thanks.

**Comment by cartertemm** [comment]
That's rather strange, and most likely debugable. Wonder if the same would occur if you were to swap shift for another modifier?

**Comment by josephsl** [comment]
Hi, perhaps. At the moment my focus is on Python 3 work, so may need to ask someone to take a look at it (note that the incomplete key registration happens with Caps lock key). Thanks.

**Comment by josephsl** [comment]
Hi,

I may need to close this as I'm about to pass the add-on to the community and need to do some high priority work before that.

Thanks.
