### ISSUE TITLE
Addon won't install properly after updating from NVDA 2019.2 to 2020.2

### ISSUE THREAD

**Issue by ryok141** [josephsl/resourceMonitor#7]
HI there. after I updated NVDA from 2019.2 to 2020.2, resource monitor refuses to get enabled no matter what I do. I tried disabling/enabling the addon and restarting NVDA but no luck. I also tried reinstalling the addon but no luck. I'm using windows 10 version 2019.9. Thanks much.

**Comment by josephsl** [comment]
Hi, which version of the Resource monitor did you install or try to install? Thanks.

**Comment by ryok141** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by josephsl** [comment]
Hi, hmmm, which browser did you use to download the add-on? What error did you get when trying to install Resource Monitor? Thanks.

**Comment by ryok141** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by josephsl** [comment]
Hi,

Okay, try this:

1. Go to Start, enter "explore NVDA" (without quotes) and press Enter.
2. Open "add-ons" folder.
3. Delete any folder with the name that starts with "resourceMonitor".
4. Restart NVDA.
5. Reinstall Resource Monitor.

Thanks.

**Comment by ryok141** [comment]
Hi there. I’m really sorry for the late reply.I just wanted to tell you that I just tried what you recommended and it works!Thanks much for your help, I really appreciate it.Best regards.Ahmad From: Joseph LeeSent: Sunday, August 2, 2020 6:27 PMTo: josephsl/resourceMonitorCc: ryok141; AuthorSubject: Re: [josephsl/resourceMonitor] Addon won't install properly after updating from NVDA 2019.2 to 2020.2 (#7) Hi,Okay, try this:Go to Start, enter "explore NVDA" (without quotes) and press Enter.Open "add-ons" folder.Delete any folder with the name that starts with "resourceMonitor".Restart NVDA.Reinstall Resource Monitor.Thanks.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.  .

**Comment by josephsl** [comment]
Hi,

Glad it is working for you. Let me know if you need further assistance.
