### ISSUE TITLE
Hotkey and chinese inputf

### ISSUE THREAD

**Issue by sine-w** [josephsl/resourceMonitor#9]
#description of issue
Under chinese input method, we use shift key to change between chinese input mode or eng mode.
Normally if other nvda hotkey contain shift, it will not trigger the chinese input to shift input mode.
However using resource monitor, the below problem will arise
1. under chinese input mode
2. ppress nvda shift 2 to read ram usage
3. input method is changed to eng mode
4. I have to manually press shift again to change back to chinese input mode

**Comment by josephsl** [comment]
Hi, is this the case with all Chinese input methods? If so, the best solution now is reassigning Resource Monitor commands to something else on your system. Thanks.

**Comment by josephsl** [comment]
Hi,

Haven't heard from the reporter for a while, closing.

Thanks.
